version: '3.1'
services:

  performance-frontend:
    container_name: performance-frontend
    build:
      context: ./
    ports:
    - 3030:3030
    networks:
      - performance_network
networks:
  performance_network:
          external: true

