version: '3.1'
services:

  icontap-frontend:
    container_name: icontap-frontend
    build:
      context: ./
    ports:
    - 3000:3000
    networks:
      - icontap_network
networks:
  icontap_network:
          external: true

